---
# Home Assistant component
# # https://www.home-assistant.io/docs/configuration/basic/

homeassistant:
  # Home Assistant Instance Name
  name: Connock-Adams Home

  # Units
  unit_system: metric
  temperature_unit: C

  # Timezone
  time_zone: Europe/London

  # Customize individual entities
  customize: !include_dir_merge_named ../customizations/entities

  # Custimize all entities in a domain
  customize_domain: !include_dir_merge_named ../customizations/domains

  # Custimize entities based on a matching pattern
  customize_glob: !include_dir_merge_named ../customizations/globs
