# Main Configuration

# Main Settings
# https://www.home-assistant.io/docs/configuration/basic/
homeassistant:
  name: Connock-Adams Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_elevation
  unit_system: metric
  temperature_unit: C
  time_zone: Europe/London
  # Customize
  # https://www.home-assistant.io/docs/configuration/customizing-devices/
  customize_glob: !include config/customize_glob.yaml
  customize: !include config/customize.yaml

  # Authentication Providers
  auth_providers:
    - type: homeassistant

  # Packages
  # https://home-assistant.io/docs/configuration/packages/ 
  packages: !include_dir_named packages

# Lovelace UI
# https://www.home-assistant.io/lovelace/
# https://www.home-assistant.io/lovelace/yaml-mode/
lovelace:

# HTTP
# https://home-assistant.io/components/http/
http: !include config/http.yaml

# API
# https://www.home-assistant.io/components/api/
# https://developers.home-assistant.io/docs/en/external_api_rest.html
# Depends upon the HTTP component
api:

# Cloud
# https://www.nabucasa.com/config/
cloud:

# Config
# https://www.home-assistant.io/components/config/
config:

# HASS.io
hassio:

# Recorder
# https://www.home-assistant.io/components/recorder/
recorder:
  purge_keep_days: 7
  purge_interval: 1

# History
# https://www.home-assistant.io/components/history
history: !include config/history.yaml

# Logbook
# Note: All entries need to also be defined in recorder.yaml
# https://www.home-assistant.io/components/logbook/
logbook: !include config/logbook.yaml

# Frontend
# https://www.home-assistant.io/components/frontend/
frontend:
  themes: !include_dir_merge_named themes

# Discovery
# https://www.home-assistant.io/components/discovery/
discovery: !include config/discovery.yaml

# Map
# https://www.home-assistant.io/components/system_health/
map:

# System Health
system_health:

# Notify
# https://www.home-assistant.io/components/notify/
# https://www.home-assistant.io/components/notify.group/
notify: !include config/notify.yaml

# Update Settings
# https://www.home-assistant.io/components/updater/
updater:
  include_used_components: true

# iOS Support
# https://www.home-assistant.io/docs/ecosystem/ios/
ios:

# Mobile App
mobile_app:

# Zones
# https://www.home-assistant.io/components/zone/
zone: !include config/zones.yaml

# Person
# https://www.home-assistant.io/components/person/
person: !include config/person.yaml

# Scenes
# https://www.home-assistant.io/docs/scene/editor/
scene: !include scenes.yaml

# Twilio 
# https://www.home-assistant.io/components/twilio/
# https://www.home-assistant.io/components/twilio_sms/
twilio:
  account_sid: !secret twilio_sid
  auth_token: !secret twilio_auth_token

# Honeywell Evohome
# https://www.home-assistant.io/integrations/evohome/
evohome:
  username: !secret evohome_username
  password: !secret evohome_password
  location_idx: 1
  scan_interval: 180

# Ring
# https://www.home-assistant.io/integrations/ring/
ring:
  username: !secret ring_username
  password: !secret ring_password