# HTTP
# https://home-assistant.io/components/http/

base_url: !secret http_base_url
use_x_forwarded_for: true
trusted_proxies:
  - 10.1.2.13/32 # IP Address of Traefix Proxy
ip_ban_enabled: True
login_attempts_threshold: 3