# Person
# https://www.home-assistant.io/components/person/

# Jon
- name: Jon
  id: jon
  user_id: 7d12341fc1434391b090c88ba0cdd8e3
  device_trackers:
    - device_tracker.jonathan_iphone

# Lee
- name: Lee
  id: lee
  user_id: fdf62a5a85bc46ff8bf1a7f3f2070b6f
  device_trackers:
    - device_tracker.lee_iphone