# Person
# https://www.home-assistant.io/components/person/

# Jon
- name: Jon
  id: jon
  user_id: 7d12341fc1434391b090c88ba0cdd8e3
  device_trackers:
    - device_tracker.jonathans_iphone_x

# Lee
- name: Lee
  id: lee
  user_id: b8d967ea2f044aa5a00f8b76d653fb5b
  device_trackers:
    - device_tracker.lees_iphone_x