---
# Automatic pull of updated config from github if Travis CI build is successful
# https://www.home-assistant.io/components/travisci/

alias: Update HA Config On Successful TravisCI Build
trigger:
  - platform: state
    entity_id: sensor.jonathanadams_home_assistant_config_last_build_id
condition:
  - condition: state
    entity_id: sensor.jonathanadams_home_assistant_config_last_build_state
    state: "passed"
action:
  - service: hassio.addon_start
    data:
      addon: "core_git_pull"
