# Sonoff S20

# Basic Config
esphome:
  name: garden_decking_lights
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password

logger:

api:
  reboot_timeout: 15min

ota:
  password: !secret esphome_ota_password

time:
  - platform: sntp
    id: sntp_time

# Device Specific Config
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Garden Decking Lights Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Garden Decking Lights Status"

sensor:
  - platform: wifi_signal
    name: "Garden Decking Lights WiFi Signal"
    update_interval: 60s

switch:
  - platform: gpio
    name: "Garden Decking Lights"
    pin: GPIO12
    id: relay

status_led:
  pin: GPIO13