# Sonoff S20

# Basic Config
esphome:
  name: master_bedroom_lee_lamp
  platform: ESP8266
  board: esp01_1m

wifi:
  ssid: !secret esphome_wifi_ssid
  password: !secret esphome_wifi_password

logger:

api:
  reboot_timeout: 15min

ota:
  password: !secret esphome_ota_password

time:
  - platform: sntp
    id: sntp_time

# Device Specific Config
binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Master Bedroom Lee Lamp Button"
    on_press:
      - switch.toggle: relay
  - platform: status
    name: "Master Bedroom Lee Lamp Status"

sensor:
  - platform: wifi_signal
    name: "Master Bedroom Lee Lamp WiFi Signal"
    update_interval: 60s

switch:
  - platform: gpio
    name: "Master Bedroom Lee Lamp"
    pin: GPIO12
    id: relay

status_led:
  pin: GPIO13