
# Alexa Component
# https://www.home-assistant.io/components/alexa.smart_home/
# https://www.home-assistant.io/components/alexa.flash_briefings/
# https://www.nabucasa.com/config/amazon_alexa/
# https://github.com/mike-grant/haaska

alexa:
  smart_home:
    filter:
      include_domains:
        - switch
        - light
        - climate
        - media_player
        - scene

# Alexa Media Player Compenent
# https://github.com/keatontaylor/alexa_media_player

alexa_media:
  accounts:
    - email: !secret amazon_alexa_username
      password: !secret amazon_alexa_password
      url: amazon.co.uk
      exclude_devices:
        - "This Device"

# Customizations
homeassistant:
  customize:
    media_player.bedroom:
      friendly_name: Bedroom Echo
      icon: mdi:amazon-alexa
    media_player.kitchen:
      friendly_name: Kitchen Echo
      icon: mdi:amazon-alexa
    media_player.living_room:
      friendly_name: Living Room Echo Dot
      icon: mdi:amazon-alexa
    media_player.office:
      friendly_name: Office Echo Dot
      icon: mdi:amazon-alexa