# Sensors
sensor:
  - platform: template
    sensors:
      # Hallway
      climate_hallway_faults:
        friendly_name: "Radiator Hallway Faults"
        value_template: >-
          {% if state_attr('climate.hallway', 'status').active_faults %}
            {% if state_attr('climate.hallway', 'status').active_faults[0].fault_type == 'TempZoneActuatorLowBattery' %}
              Low Battery
            {% endif %}
              Fault Detected
          {% else %}
            Functioning Normally
          {% endif %}
        icon_template: >-
          {% set fault_level = states('sensor.climate_hallway_faults') %}
          {% if fault_level == 'Low Battery' %}
            mdi:alert
          {% elif fault_level == 'Fault Detected' %}
            mdi:alert
          {% else %}
            mdi:check-circle
          {% endif %}
  
      # Living Room
      climate_living_room_faults:
        friendly_name: "Radiator Living Room Faults"
        value_template: >-
          {% if state_attr('climate.living_room', 'status').active_faults %}
            {% if state_attr('climate.living_room', 'status').active_faults[0].fault_type == 'TempZoneActuatorLowBattery' %}
              Low Battery
            {% endif %}
              Fault Detected
          {% else %}
            Functioning Normally
          {% endif %}
        icon_template: >-
          {% set fault_level = states('sensor.climate_living_room_faults') %}
          {% if fault_level == 'Low Battery' %}
            mdi:alert
          {% elif fault_level == 'Fault Detected' %}
            mdi:alert
          {% else %}
            mdi:check-circle
          {% endif %}

      # Kitchen
      climate_kitchen_faults:
        friendly_name: "Radiator Kitchen Faults"
        value_template: >-
          {% if state_attr('climate.kitchen', 'status').active_faults %}
            {% if state_attr('climate.kitchen', 'status').active_faults[0].fault_type == 'TempZoneActuatorLowBattery' %}
              Low Battery
            {% endif %}
              Fault Detected
          {% else %}
            Functioning Normally
          {% endif %}
        icon_template: >-
          {% set fault_level = states('sensor.climate_kitchen_faults') %}
          {% if fault_level == 'Low Battery' %}
            mdi:alert
          {% elif fault_level == 'Fault Detected' %}
            mdi:alert
          {% else %}
            mdi:check-circle
          {% endif %}
  

      # Office
      climate_office_faults:
        friendly_name: "Radiator Office Faults"
        value_template: >-
          {% if state_attr('climate.office', 'status').active_faults %}
            {% if state_attr('climate.office', 'status').active_faults[0].fault_type == 'TempZoneActuatorLowBattery' %}
              Low Battery
            {% endif %}
              Fault Detected
          {% else %}
            Functioning Normally
          {% endif %}
        icon_template: >-
          {% set fault_level = states('sensor.climate_office_faults') %}
          {% if fault_level == 'Low Battery' %}
            mdi:alert
          {% elif fault_level == 'Fault Detected' %}
            mdi:alert
          {% else %}
            mdi:check-circle
          {% endif %}

      # Bedroom
      climate_bedroom_faults:
        friendly_name: "Radiator Bedroom Faults"
        value_template: >-
          {% if state_attr('climate.bedroom', 'status').active_faults %}
            {% if state_attr('climate.bedroom', 'status').active_faults[0].fault_type == 'TempZoneActuatorLowBattery' %}
              Low Battery
            {% endif %}
              Fault Detected
          {% else %}
            Functioning Normally
          {% endif %}
        icon_template: >-
          {% set fault_level = states('sensor.climate_bedroom_faults') %}
          {% if fault_level == 'Low Battery' %}
            mdi:alert
          {% elif fault_level == 'Fault Detected' %}
            mdi:alert
          {% else %}
            mdi:check-circle
          {% endif %}

      # Spare Room
      climate_spare_room_faults:
        friendly_name: "Radiator Spare Room Faults"
        value_template: >-
          {% if state_attr('climate.spare_room', 'status').active_faults %}
            {% if state_attr('climate.spare_room', 'status').active_faults[0].fault_type == 'TempZoneActuatorLowBattery' %}
              Low Battery
            {% endif %}
              Fault Detected
          {% else %}
            Functioning Normally
          {% endif %}
        icon_template: >-
          {% set fault_level = states('sensor.climate_spare_room_faults') %}
          {% if fault_level == 'Low Battery' %}
            mdi:alert
          {% elif fault_level == 'Fault Detected' %}
            mdi:alert
          {% else %}
            mdi:check-circle
          {% endif %}

      # Bathroom
      climate_bathroom_faults:
        friendly_name: "Radiator Bathroom Faults"
        value_template: >-
          {% if state_attr('climate.bathroom', 'status').active_faults %}
            {% if state_attr('climate.bathroom', 'status').active_faults[0].fault_type == 'TempZoneActuatorLowBattery' %}
              Low Battery
            {% endif %}
              Fault Detected
          {% else %}
            Functioning Normally
          {% endif %}
        icon_template: >-
          {% set fault_level = states('sensor.climate_bathroom_faults') %}
          {% if fault_level == 'Low Battery' %}
            mdi:alert
          {% elif fault_level == 'Fault Detected' %}
            mdi:alert
          {% else %}
            mdi:check-circle
          {% endif %}