# Home Assistant Maintenance

# Automation
automation:
  - alias: HASSIO Weekly Snapshot
    trigger:
      - platform: time
        at: "3:00:00"
    condition:
      condition: time
      weekday:
        - sun
    action:
    - service: hassio.snapshot_full
      data_template:
        name: "Automated Backup {{ now().strftime('%Y-%m-%d') }}"

# Sensor
sensor:
  - platform: command_line
    name: HA Installed Version
    command: "cat .HA_VERSION"
    scan_interval: 3600
