# Home Assistant Maintenance

# Automation
automation:
  - alias: HASSIO Weekly Snapshot
    trigger:
      - platform: time
        at: "3:00:00"
    condition:
      condition: time
      weekday:
        - sun
    action:
    - service: hassio.snapshot_full
      data_template:
        name: "Automated Backup {{ now().strftime('%Y-%m-%d') }}"

# Sensor
sensor:
  # HA Installed Version
  - platform: command_line
    name: HA Installed Version
    command: "cat .HA_VERSION"
    scan_interval: 3600
  # HA Latest Version Available
  - platform: command_line
    command: python3 -c "import requests; print(requests.get('https://s3.amazonaws.com/hassio-version/stable.json').json()['homeassistant']['default'])"
    name: HA Upstream Version
    scan_interval: 3600

