# House Alarm

## Sensor
sensor:
  - platform: mqtt
    name: Arming Status
    state_topic: "home/alarm/arming_status"
    icon: mdi:alarm-bell

  - platform: mqtt
    name: Sounder Status
    state_topic: "home/alarm/sounder_status"
    icon: mdi:alarm-bell