# Living Room

# Components

media_player:
  # Yamaha Amplifier
  # https://www.home-assistant.io/components/yamaha/
  - platform: yamaha
    name: Living Room Amplifier
    host: !secret living_room_amp_ip
    source_names:
      HDMI1: "HDMI1 - Sky Q"
    source_ignore:
      - "Deezer"
      - "JUKE"
      - "MusicCast Link"
      - "Qobuz"
      - "Spotify"
      - "Tuner"
      - "TIDAL"
      - "USB"
      - "AUDIO1"
      - "AUDIO2"
      - "AUDIO3"
      - "AV1"
      - "AV2"
      - "AV3"

  # Sony Bravia TV
  # https://www.home-assistant.io/components/braviatv/
  - platform: braviatv
    name: Living Room TV
    host: !secret living_room_tv_ip

# Customize
homeassistant:
  customize:
    # Left Lamp (Sonoff S20 #1)
    switch.sonoff_s20_1:
      friendly_name: Left Lamp
      icon: mdi:lamp

    # Right Lamp (Sonoff S20 #2)
    switch.sonoff_s20_2:
      friendly_name: Right Lamp
      icon: mdi:lamp

    # Living Room Amplifier
    media_player.living_room_amplifier:
      icon: mdi:surround-sound

    # Living Room TV
    media_player.living_room_tv:
      icon: mdi:television