# Living Room

# Components

# Yamaha Amplifier
# https://www.home-assistant.io/components/yamaha/
media_player:
  - platform: yamaha
    host: !secret living_room_amp_ip
    source_names:
      HDMI1: "Sky Q"

# Sony Bravia TV
# https://www.home-assistant.io/components/braviatv/
media_player:
  - platform: braviatv
    host: !secret living_room_tv_ip

# Customize
homeassistant:
  customize:
    # Sonoff S20 #1
    switch.sonoff_s20_1:
      friendly_name: Left Lamp
      icon: mdi:lamp

    # Sonoff S20 #2
    switch.sonoff_s20_2:
      friendly_name: Right Lamp
      icon: mdi:lamp