# Master Medroom

# Group
group:
  master_bedroom_all_lights:
    name: Bedroom All Lights
    entities:
      - group.master_bedroom_all_lamps
  master_bedroom_all_lamps:
    name: Bedroom Lamps
    entities:
      - switch.master_bedroom_jon_lamp
      - switch.master_bedroom_lee_lamp

# Customize
homeassistant:
  customize:
    # Lee's Bedside Lamp (Sonoff S20 #1)
    switch.master_bedroom_lee_lamp:
      friendly_name: Lee Lamp
      icon: mdi:lamp

    # Jon's Bedside Lamp (Sonoff S20 #2)
    switch.master_bedroom_jon_lamp:
      friendly_name: Jon Lamp
      icon: mdi:lamp

# Alexa
alexa:
  smart_home:
    filter:
      include_entities:
        - group.master_bedroom_all_lights
        - group.master_bedroom_all_lamps
    entity_config:
      switch.master_bedroom_lee_lamp:
        name: Lee Lamp
        display_categories: LIGHT
      switch.master_bedroom_jon_lamp:
        name: Jon Lamp
        display_categories: LIGHT
      group.master_bedroom_all_lights:
        name: Bedroom Lights
        display_categories: LIGHT
      group.master_bedroom_all_lamps:
        name: Bedroom Lamps
        display_categories: LIGHT