# Travis CI
# https://www.home-assistant.io/components/travisci/

# Sensors
sensor:
  - platform: travisci
    api_key: !secret travisci_api_key
    repository: "Home-Assistant-Configuration"
    monitored_conditions:
      - last_build_id
      - last_build_state

# Automation
automation:
  - alias: Update HA Config On Successful TravisCI Build
    trigger:
      - platform: state
        entity_id: sensor.home_assistant_config_last_build_id
    condition:
      - condition: state
        entity_id: sensor.home_assistant_config_last_build_state
        state: 'passed'
    action:   
      - service: hassio.addon_start
        data: 
          addon: "core_git_pull"

# Customize
homeassistant:
  customize: 
    sensor.travis_build_label:
      hidden: true
    sensor.travis_status:
      hidden: true